name = "Lazy"
uuid = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
version = "0.14"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "â‰¥ 0.4.4"
julia = "0.7.0, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
